M48
; DRILL file {KiCad (6.0.7)} date Wed Aug  3 23:31:25 2022
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2022-08-03T23:31:25+02:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,(6.0.7)
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C3.250
%
G90
G05
T1
X127.285Y-76.05
X138.715Y-76.05
X147.285Y-76.05
X158.715Y-76.05
T0
M30
